#!/bin/sh
set -eu

lb config noauto \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --linux-flavours amd64 \
    --binary-images iso-hybrid \
    --bootloader grub-efi \
    --bootappend-live "boot=live components hostname=humanix username=humanix quiet splash" \
    --iso-application "Humanix Live Appliance" \
    --iso-volume "HUMANIX_LIVE" \
    --system live \
    --security false \
    --updates false \
    --memtest none \
    --win32-loader false \
    --apt-indices false \
    --apt-recommends false \
    --verbose \
    "${@}"
